---
title: "R Notebook"
output: html_notebook
---

# Loading Data

```{r}
raw_data <- read.csv("C:/Users/Ham/OneDrive - Bina Nusantara/Ham/Binus/Semester 5/Design Analysis and Experiment/AOL/penguins_preprocessed.csv", header=T)

head(raw_data)

```

# Data Cleaning

```{r}
# Data Cleaning 
data <- raw_data

## Removing NA
data <- na.omit(data)

head(data)
```

# EDA

```{r}
boxplot(flipper_length_mm~species, data=data)
table(data$Education.Level)
```

```{r}
table(data$species)
```

# ANOVA

```{r}
anova <- aov(flipper_length_mm~species, data=data)
```

```{r}
summary(anova)
```

```{r}
anova(anova)
```

# Model Adequacy: Residuals Analysis

## Hypothesis Testing

```{r}
library(car)
leveneTest(anova)
```

```{r}
library(lmtest)
dwtest(anova)
```

```{r}
shapiro.test(resid(anova))
```

## Plot

```{r}
plot(anova)
```

# Post-Hoc

```{r}
TukeyHSD(anova)
```

```{r}
data.
```

```{r}
library(ggplot2)
library(plyr)

mu <- ddply(data, "species", summarise, grp.mean=mean(flipper_length_mm))

ggplot(data, aes(x=flipper_length_mm, fill=species, color=species)) +
  geom_histogram(position="identity", alpha=0.5)
```
